_target_: sklearn.compose.ColumnTransformer
remainder: drop
verbose_feature_names_out: False

transformers:

  # Numeric Pipeline (Impute + Scale)
  - - num_prep
    - _target_: sklearn.pipeline.make_pipeline
      _args_:
        - _target_: sklearn.impute.SimpleImputer
          strategy: median
        - _target_: sklearn.preprocessing.StandardScaler
    - _target_: sklearn.compose.make_column_selector
      dtype_include: number

  # Categorical Pipeline(Impute + OHE)
  - - cate_prep
    - _target_: sklearn.pipeline.make_pipeline
      _args_:
        - _target_: sklearn.impute.SimpleImputer
          strategy: most_frequent
        - _target_: sklearn.preprocessing.OneHotEncoder
          handle_unknown: ignore
          sparse_output: False
    - _target_: sklearn.compose.make_column_selector
      dtype_include: category