_target_: sklearn.compose.ColumnTransformer
remainder: passthrough
verbose_feature_names_out: False

transformers:
  # convert province and city to proper categorical dtype
  - - convert_to_categorical
    - _target_: malnutrition_risk.features.ToCategory
    - ${dataset.schema.geo_cols}

  # drop highly correlated columns (TripCountNonAirNonPilgrimage_95to99)
  - - drop_high_corr_cols
    - drop
    - ${dataset.schema.high_corr_cols}

  # drop meta-data columns (id, Parent_Id, has_label)
  - - drop_metadata_cols
    - drop
    - ${dataset.schema.metadata_cols}

  # Numeric Pipeline (Impute + Scale)
  - - num_prep
    - _target_: sklearn.pipeline.make_pipeline
      _args_:
        - _target_: sklearn.impute.SimpleImputer
          strategy: median
        - _target_: sklearn.preprocessing.StandardScaler
    - ${dataset.schema.numeric_cols}

  # Categorical Pipeline(Impute + OHE)
  - - cate_prep
    - _target_: sklearn.pipeline.make_pipeline
      _args_:
        - _target_: sklearn.impute.SimpleImputer
          strategy: most_frequent
        - _target_: sklearn.preprocessing.OneHotEncoder
          handle_unknown: ignore
          sparse_output: False
    - ${dataset.schema.categorical_cols}