_target_: sklearn.compose.ColumnTransformer
remainder: drop
verbose_feature_names_out: false
transformers:
  - - all
    - passthrough
    - _target_: sklearn.compose.make_column_selector
      pattern: '.*'