curation:
  _target_: malnutrition_risk.data.curator.DataCurator
  target: ${dataset.target}
  group: ${dataset.group}
  label_indicator_col: ${dataset.schema.label_indicator_col}
  no_nan_cols:
    - ISBimarKhas
    - IsMalool
    - Malool_shedat
    - IsBehzisti_AfzayeshMostamari
    - IsKomite_AfzayeshMostamari
    - IsKomite_AfzayeshMostamariSayer
    - Has_Saham_Edalat
    - IsRetired_Asli
    - IsRetired_Tabaie
    - is_bime_darman
    - IsBimePardaz

splitting:
  target: ${dataset.target}
  group: ${dataset.group}
  test_size: 0.2
  val_size: 0.2
  random_state: ${seed}
